name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password   # replace with a strong root password
          MYSQL_DATABASE: papyrus              # test database name
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set up database environment variables
      run: |
        echo "SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/papyrus?useSSL=false&serverTimezone=UTC" >> $GITHUB_ENV
        echo "SPRING_DATASOURCE_USERNAME=root" >> $GITHUB_ENV
        echo "SPRING_DATASOURCE_PASSWORD=root_password" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B package --file ris21/backend/pom.xml
